### ISSUE TITLE
Is the program able to retrieve back the VRAM used by Topaz Video AI?

### ISSUE THREAD

**Issue by acoolrocket** [sbcarp/TopazVideoPauser#2]
So it works, but my VRAM is still at 5.4GB used. When I actually stop processing and close Video AI it goes down 2-3GB. So is it possible for this tool to retrieve back the VRAM or is it not possible given it needs to park that VRAM?

**Comment by sbcarp** [comment]
The tool works by suspending the Video AI processes, it doesn't have control to the app internal logic, so unfortunately there's no way we can free the VRAM on pause.
