### ISSUE TITLE
ffmpeg command line only

### ISSUE THREAD

**Issue by tyd57i** [sbcarp/TopazVideoPauser#3]
I mostly don't use topaz shell, but run a preconfigured command line with topaz ffmpeg.exe.
Can your utility be extended to pause and resume ffmpeg?

**Comment by sbcarp** [comment]
Sorry, there's no plan to support this yet, the tool works by detecting ffmpeg.exe processes spawned by topaz, other programs rely on ffmpeg will be affected if we remove the constraint and pause any ffmpeg.exe processes. It's possible to make it optional and not on by default, but requires more work, so this feature may not be availiable in the near future.

Thanks for your feedback!
