### ISSUE TITLE
[Request] Low Priority CPU

### ISSUE THREAD

**Issue by Rootkit-** [sbcarp/TopazVideoPauser#4]
Hey I'm wondering if you can impliment an option like cpu cores, to add an option to autoset ffmpeg CPU Priority Low.

Comment not your program, but Topaz its insane they don't have this stuff, like repositioning queue and CPU priority and pause all implimented into the software its fairly simple things.

**Comment by sbcarp** [comment]
Hi, I think it already have the option to limit how many cores ffrmpeg will use, it's an experimental feature tho, but you can right click on the icon to use it
