### ISSUE TITLE
Does not pause the video render and the tray icon is a yellow lock

### ISSUE THREAD

**Issue by ratmaiden** [sbcarp/TopazVideoPauser#5]
I've tried pausing the render, but it won't stop nor freeze the UI at all. I've tried multiple times. I'm still using the 2.2.0 version of Topaz though, maybe that's the problem? Can't update, because it's on my PC from work and they've frozen any app installs for some odd reason.

**Comment by sbcarp** [comment]
Hi, 2.2.0 is little too old to support, but if it's an esay fix I'll do it, what is the process name for your Topaz program? You may find it in Task Manager -> Details -> check for process has topaz keyword or anything related

**Comment by ratmaiden** [comment]
Hi, thanks for replying. Its process name is "Topaz Video Enhance AI.exe" I
hope it works, but if it won't, it's fine. No pressure.

**Comment by sbcarp** [comment]
Okay, I added the process name to the app, you can download the latest version to try it, hope it works!

**Comment by ratmaiden** [comment]
Hey man, you see the thing is, it still doesn't work. However, it's fine. It's not your fault, it's just the shitty company policy's fault. I'll probably just use my home PC for enhancing videos. Thanks for trying, at least.

https://github.com/sbcarp/TopazVideoPauser/assets/103858167/876cb7c2-08c2-49e4-9da5-22e275cef969

**Comment by sbcarp** [comment]
Thanks for the video. 

I see what's going on here, Topaz Video 2.x doesn't spawn ffmpeg process for video tasks, but doing all the work in it's own process. I think there's a way to fix it without modifying current project structure. 

New version is published, welcome to try.

**Comment by ratmaiden** [comment]
Hey man, great news. IT WORKS!!! Great job, and thanks. I really appreciate it!
